/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppVardeVernRouteImport } from './routes/_app/varde-vern'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppLlmRouterRouteImport } from './routes/_app/llm-router'
import { Route as AppInvitesRouteImport } from './routes/_app/invites'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppGrantsRouteImport } from './routes/_app/grants'
import { Route as AppAccessRouteImport } from './routes/_app/access'
import { Route as AppConfigurationIndexRouteImport } from './routes/_app/configuration/index'
import { Route as AuthOpenidCallbackRouteImport } from './routes/auth/openid/callback'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVardeVernRoute = AppVardeVernRouteImport.update({
  id: '/varde-vern',
  path: '/varde-vern',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppLlmRouterRoute = AppLlmRouterRouteImport.update({
  id: '/llm-router',
  path: '/llm-router',
  getParentRoute: () => AppRoute,
} as any)
const AppInvitesRoute = AppInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppGrantsRoute = AppGrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigurationIndexRoute = AppConfigurationIndexRouteImport.update({
  id: '/configuration/',
  path: '/configuration/',
  getParentRoute: () => AppRoute,
} as any)
const AuthOpenidCallbackRoute = AuthOpenidCallbackRouteImport.update({
  id: '/auth/openid/callback',
  path: '/auth/openid/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/grants': typeof AppGrantsRoute
  '/help': typeof AppHelpRoute
  '/invites': typeof AppInvitesRoute
  '/llm-router': typeof AppLlmRouterRoute
  '/users': typeof AppUsersRoute
  '/varde-vern': typeof AppVardeVernRoute
  '/auth/openid/callback': typeof AuthOpenidCallbackRoute
  '/configuration/': typeof AppConfigurationIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/access': typeof AppAccessRoute
  '/grants': typeof AppGrantsRoute
  '/help': typeof AppHelpRoute
  '/invites': typeof AppInvitesRoute
  '/llm-router': typeof AppLlmRouterRoute
  '/users': typeof AppUsersRoute
  '/varde-vern': typeof AppVardeVernRoute
  '/': typeof AppIndexRoute
  '/auth/openid/callback': typeof AuthOpenidCallbackRoute
  '/configuration': typeof AppConfigurationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/access': typeof AppAccessRoute
  '/_app/grants': typeof AppGrantsRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/invites': typeof AppInvitesRoute
  '/_app/llm-router': typeof AppLlmRouterRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/varde-vern': typeof AppVardeVernRoute
  '/_app/': typeof AppIndexRoute
  '/auth/openid/callback': typeof AuthOpenidCallbackRoute
  '/_app/configuration/': typeof AppConfigurationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/access'
    | '/grants'
    | '/help'
    | '/invites'
    | '/llm-router'
    | '/users'
    | '/varde-vern'
    | '/auth/openid/callback'
    | '/configuration/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/access'
    | '/grants'
    | '/help'
    | '/invites'
    | '/llm-router'
    | '/users'
    | '/varde-vern'
    | '/'
    | '/auth/openid/callback'
    | '/configuration'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/access'
    | '/_app/grants'
    | '/_app/help'
    | '/_app/invites'
    | '/_app/llm-router'
    | '/_app/users'
    | '/_app/varde-vern'
    | '/_app/'
    | '/auth/openid/callback'
    | '/_app/configuration/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthOpenidCallbackRoute: typeof AuthOpenidCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/varde-vern': {
      id: '/_app/varde-vern'
      path: '/varde-vern'
      fullPath: '/varde-vern'
      preLoaderRoute: typeof AppVardeVernRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/llm-router': {
      id: '/_app/llm-router'
      path: '/llm-router'
      fullPath: '/llm-router'
      preLoaderRoute: typeof AppLlmRouterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invites': {
      id: '/_app/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof AppInvitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grants': {
      id: '/_app/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof AppGrantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access': {
      id: '/_app/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuration/': {
      id: '/_app/configuration/'
      path: '/configuration'
      fullPath: '/configuration/'
      preLoaderRoute: typeof AppConfigurationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/openid/callback': {
      id: '/auth/openid/callback'
      path: '/auth/openid/callback'
      fullPath: '/auth/openid/callback'
      preLoaderRoute: typeof AuthOpenidCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccessRoute: typeof AppAccessRoute
  AppGrantsRoute: typeof AppGrantsRoute
  AppHelpRoute: typeof AppHelpRoute
  AppInvitesRoute: typeof AppInvitesRoute
  AppLlmRouterRoute: typeof AppLlmRouterRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVardeVernRoute: typeof AppVardeVernRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConfigurationIndexRoute: typeof AppConfigurationIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessRoute: AppAccessRoute,
  AppGrantsRoute: AppGrantsRoute,
  AppHelpRoute: AppHelpRoute,
  AppInvitesRoute: AppInvitesRoute,
  AppLlmRouterRoute: AppLlmRouterRoute,
  AppUsersRoute: AppUsersRoute,
  AppVardeVernRoute: AppVardeVernRoute,
  AppIndexRoute: AppIndexRoute,
  AppConfigurationIndexRoute: AppConfigurationIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthOpenidCallbackRoute: AuthOpenidCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
